require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - test/dummy/db/schema.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - lib/generic_job.rb

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - test/dummy/bin/*
