AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Metrics/LineLength:
  Enabled: true
  Exclude:
    - test/dummy/config/environments/development.rb
    - test/dummy/config/environments/production.rb
    - test/dummy/config/environments/test.rb
    - test/dummy/config/application.rb
    - test/dummy/config/puma.rb
    - test/dummy/config/initializers/content_security_policy.rb
    - test/dummy/config/initializers/wrap_parameters.rb
    - test/dummy/config/initializers/backtrace_silencers.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - lib/generic_job.rb

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - test/generic_job_test.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - bin/rails
    - test/dummy/bin/*

Style/MethodDefParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - test/dummy/bin/*