AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Enabled: true
  Exclude:
    - test/dummy/config/environments/development.rb
    - test/dummy/config/environments/production.rb
    - test/dummy/config/environments/test.rb
    - test/dummy/config/application.rb
    - test/dummy/config/puma.rb
    - test/dummy/config/initializers/content_security_policy.rb
    - test/dummy/config/initializers/wrap_parameters.rb
    - test/dummy/config/initializers/backtrace_silencers.rb

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - test/generic_job_test.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - bin/rails
    - test/dummy/bin/*

Style/MixinUsage:
  Enabled: true
  Exclude:
    - test/dummy/bin/*