require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - test/dummy/db/schema.rb
    - test/dummy/config/environments/development.rb

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  Exclude:
    - test/dummy/config/environments/production.rb

Metrics/LineLength:
  Enabled: true
  Exclude:
    - generic_job.gemspec
    - test/dummy/Rakefile
    - test/dummy/config/environments/development.rb
    - test/dummy/config/environments/production.rb
    - test/dummy/config/environments/test.rb
    - test/dummy/config/application.rb
    - test/dummy/config/puma.rb
    - test/dummy/config/initializers/content_security_policy.rb
    - test/dummy/config/initializers/wrap_parameters.rb
    - test/dummy/config/initializers/backtrace_silencers.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - lib/generic_job.rb

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - bin/rails
    - test/dummy/bin/*

Style/MethodDefParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - test/dummy/bin/*

Style/StringLiterals:
  Enabled: true
  Exclude:
    - test/dummy/config/environments/production.rb
